### ISSUE TITLE
NullPointerException при запуске приложения

### ISSUE THREAD

**Issue by igorigorigorigor** [vfarafonov/DroidShoter#2]
Mac OS X El Capitan Версия 10.11.3

```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

```
1. Подключил Nexus 5 (usb-debugging ON)
2. Запустил приложение
   `java -jar  ScreenShoter-1.0.jar
   Exception in thread "main" java.lang.NullPointerException
   at javax.swing.text.Utilities.getTabbedTextWidth(Utilities.java:273)
   at javax.swing.text.Utilities.getTabbedTextWidth(Utilities.java:208)
   at javax.swing.text.PlainView.getLineWidth(PlainView.java:669)
   at javax.swing.text.PlainView.updateDamage(PlainView.java:567)
   at javax.swing.text.PlainView.insertUpdate(PlainView.java:451)
   at javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(BasicTextUI.java:1602)
   at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(BasicTextUI.java:1861)
   at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:202)
   at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:749)
   at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:708)
   at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
   at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:670)
   at javax.swing.text.JTextComponent.setText(JTextComponent.java:1718)
   at com.weezlabs.tools.android.screenshoter.ScreenshoterMainScreen.$$$setupUI$$$(ScreenshoterMainScreen.java)
   at com.weezlabs.tools.android.screenshoter.ScreenshoterMainScreen.<init>(ScreenshoterMainScreen.java:73)
   at com.weezlabs.tools.android.screenshoter.ScreenshoterMainScreen.main(ScreenshoterMainScreen.java:180)
   `

**Comment by vfarafonov** [comment]
Спасибо. Подтверждаю проблему. В ближайшее время решу
Thanks. Will solve this ASAP

**Comment by vfarafonov** [comment]
Как быстрый фикс я обновил версию в секции релизов https://github.com/vfarafonov/DroidShoter/releases/latest. На os x устройствах, которые есть рядом, работает без проблем. Если есть возможность, попробуйте запустить, пожалуйста и сообщите результат.

**Comment by igorigorigorigor** [comment]
@vfarafonov 
Спасибо. Успешно запустил приложение 

```
java -jar  DroidShoterJar-1.0.stable.jar 
04:39:00 E/DeviceMonitor: Connection attempts: 1
04:39:00 E/adb: adb I  2278 203915 usb_osx.cpp:259] Found vid=18d1 pid=4ee2 serial=0966c7410de4fdf0
04:39:00 E/adb: adb I  2278 203915 usb_osx.cpp:259] 
```
